name = "tfm-survey"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "TFM_DB"
database_name = "tfm"
database_id = "e728908c-aaa2-4fed-9abe-26f6cb6473d4"
