name = "tfm-survey"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "TFM_DB"
database_name = "tfm"
database_id = "e728908c-aaa2-4fed-9abe-26f6cb6473d4"
